version: '3'

services:
  localserver:
    build: .
    ports:
      - "25961:25961"
    depends_on:
      localdb:
        condition: service_healthy
    network_mode: "host"

  localdb:
    image: postgres:16.3-alpine3.20
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d 
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: